# Generated by Django 3.0.2 on 2020-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
    ]
